markdown: kramdown
highlighter: rouge
sass:
  style: compressed

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/amit-upadhyay-it/amit-upadhyay-it.github.io/
stack_repository: https://stackoverflow.com/users/5411888/amit-upadhyay/

timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"
      image: /img/twitter-card.png

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true
  android:
    output: true

name: Amit Upadhyay â€¢ Programming Blog
description: Everything has its two sides and that's what Binomial is all about.
url: https://binomial.me

twitter:
  username: amit-upadhyay-it

logo: /img/logo-2x1.png

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - CNAME
  - icomoon-selection.json
  - readme.md
